language: node_js
node_js:
  - "10"
services:
  - postgresql
install:
  - yarn install
before_script:
  - psql -c 'create database babol_test;' -U postgres
  - 'yarn migrations:run'
script:
  - yarn test
